services:
  - type: web
    name: myblog
    env: python
    buildCommand: './build.sh'
    startCommand: 'gunicorn myproject.wsgi:application'
    plan: free
    branch: main
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4